# Generated by Django 5.0.1 on 2024-01-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('motto', models.CharField(max_length=100)),
                ('established', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
