# Generated by Django 5.0.1 on 2024-01-17 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_franchise_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.franchise')),
            ],
        ),
    ]
