# Generated by Django 5.0.1 on 2024-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height_feet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height_inches',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_pounds',
            field=models.IntegerField(null=True),
        ),
    ]
