# Generated by Django 5.0.1 on 2024-03-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_player_height_feet_alter_player_height_inches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='height_feet',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='weight_pounds',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='player',
            name='height_inches',
        ),
    ]
