# Generated by Django 5.0.1 on 2024-03-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_height_feet_player_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(null=True),
        ),
    ]
